---
comments: false
---

## Hello! 

My name's Charlie Kopp. I am a statistics geek with a passion for mental health advocacy and highlighting the unique connections that bring humans together in mind and spirit.

I am currently studying Statistics and Data Science at UCLA, but what makes me special is my personal journey through sobriety and recovery, and experience with interpersonal communication and leadership.

As a young person who has battled through addiction and mental health crises and emerged on the other side with a newfound appreciation for life, my hope is to use my quantitative skills to make a positive impact on the world around me. There are more factors than ever in the world today that drive people apart and encourage isolation, however there are equivalent resources and technologies that can counter this crisis. 

Using kindness, transparency and dedication I believe we can make this planet a place where everyone can live with dignity, comfort and joy!

Check out my [Projects](projects.qmd) page to see what I have worked on.

Check out my [Hobbies](hobbies.qmd) page to see what I do for fun.
